[package]
name = "accessible_tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
wxdragon = { git = "https://github.com/allendang/wxDragon" }
rodio = "0.19.0"
rand = "0.8.5"
lazy_static = "1.4.0"
tolk = "0.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
gilrs = "0.11.2"

[build-dependencies]
winres = "0.1.12"
